# /turtlesim2/sim:
#    ros__parameters:
#       background_b: 255
#       background_g: 86
#       background_r: 150


# Now it is usable for other namespaces
/**:
   ros__parameters:
      background_b: 255
      background_g: 86
      background_r: 150